-- full database setup, run this to create everything
-- tables -> indexes -> triggers -> procedures -> test data

SET SERVEROUTPUT ON;

-- tables

-- sponsor just has a name
CREATE TABLE Sponsor (
    name VARCHAR2(100) PRIMARY KEY
);

CREATE TABLE Conference (
    acronym      VARCHAR2(50)  PRIMARY KEY,
    name         VARCHAR2(100) NOT NULL,
    location     VARCHAR2(100),
    homepage_url VARCHAR2(150)
);

-- organizer = program committee member
CREATE TABLE Organizer (
    code        VARCHAR2(20)  PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    affiliation VARCHAR2(100),
    address     VARCHAR2(200),
    phone       VARCHAR2(20),
    email       VARCHAR2(100)
);

CREATE TABLE ResearchArea (
    area_acronym VARCHAR2(20)  PRIMARY KEY,
    area_name    VARCHAR2(100) NOT NULL,
    description  VARCHAR2(500)
);

CREATE TABLE Author (
    code        VARCHAR2(20)  PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    affiliation VARCHAR2(100),
    address     VARCHAR2(200),
    phone       VARCHAR2(20),
    email       VARCHAR2(100)
);

-- partner = company for industrial papers
CREATE TABLE Partner (
    code    VARCHAR2(20)  PRIMARY KEY,
    name    VARCHAR2(100) NOT NULL,
    address VARCHAR2(200)
);

CREATE TABLE Article (
    article_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conference_acronym   VARCHAR2(50)  NOT NULL,
    seq_number           INT           NOT NULL,
    title                VARCHAR2(200) NOT NULL,
    category             VARCHAR2(50)  NOT NULL
        CHECK (category IN ('Industrial Paper', 'Research Paper',
                            'Tutorial', 'Poster', 'Short Paper')),
    status               VARCHAR2(20) DEFAULT 'pending'
        CHECK (status IN ('pending', 'accepted', 'rejected')),
    avg_global_score     FLOAT DEFAULT 0.0,  -- redundant, kept in sync by trigger
    contact_author_code  VARCHAR2(20) NOT NULL,
    FOREIGN KEY (conference_acronym) REFERENCES Conference(acronym),
    FOREIGN KEY (contact_author_code) REFERENCES Author(code),
    CONSTRAINT unique_conference_seq UNIQUE (conference_acronym, seq_number)
);

-- sponsor <-> conference (N:M)
CREATE TABLE Sponsorship (
    sponsor_name       VARCHAR2(100),
    conference_acronym VARCHAR2(50),
    funding_date       DATE   NOT NULL,
    funded_amount      NUMBER NOT NULL CHECK (funded_amount > 0),
    PRIMARY KEY (sponsor_name, conference_acronym),
    FOREIGN KEY (sponsor_name)       REFERENCES Sponsor(name),
    FOREIGN KEY (conference_acronym) REFERENCES Conference(acronym)
);

-- committee membership
CREATE TABLE Membership (
    organizer_code     VARCHAR2(20),
    conference_acronym VARCHAR2(50),
    PRIMARY KEY (organizer_code, conference_acronym),
    FOREIGN KEY (organizer_code)     REFERENCES Organizer(code),
    FOREIGN KEY (conference_acronym) REFERENCES Conference(acronym)
);

-- 3-way bridge: organizer declares areas for a conference
CREATE TABLE AreaIndication (
    organizer_code     VARCHAR2(20),
    conference_acronym VARCHAR2(50),
    area_acronym       VARCHAR2(20),
    PRIMARY KEY (organizer_code, conference_acronym, area_acronym),
    FOREIGN KEY (organizer_code)     REFERENCES Organizer(code),
    FOREIGN KEY (conference_acronym) REFERENCES Conference(acronym),
    FOREIGN KEY (area_acronym)       REFERENCES ResearchArea(area_acronym)
);

CREATE TABLE Authorship (
    article_id  NUMBER,
    author_code VARCHAR2(20),
    PRIMARY KEY (article_id, author_code),
    FOREIGN KEY (article_id)  REFERENCES Article(article_id) ON DELETE CASCADE,
    FOREIGN KEY (author_code) REFERENCES Author(code)
);

CREATE TABLE ArticleAreaIndication (
    article_id   NUMBER,
    area_acronym VARCHAR2(20),
    PRIMARY KEY (article_id, area_acronym),
    FOREIGN KEY (article_id)   REFERENCES Article(article_id) ON DELETE CASCADE,
    FOREIGN KEY (area_acronym) REFERENCES ResearchArea(area_acronym)
);

-- partner <-> article, only for industrial papers (BR12 trigger checks this)
CREATE TABLE Contribution (
    article_id   NUMBER,
    partner_code VARCHAR2(20),
    PRIMARY KEY (article_id, partner_code),
    FOREIGN KEY (article_id)   REFERENCES Article(article_id) ON DELETE CASCADE,
    FOREIGN KEY (partner_code) REFERENCES Partner(code)
);

CREATE TABLE Review (
    code          VARCHAR2(20) PRIMARY KEY,
    review_date   DATE         NOT NULL,
    content       CLOB,
    originality   INT  CHECK (originality  BETWEEN 0 AND 10),
    significance  INT  CHECK (significance BETWEEN 0 AND 10),
    quality       INT  CHECK (quality      BETWEEN 0 AND 10),
    global_score  INT  CHECK (global_score BETWEEN 0 AND 10),
    comments      CLOB,
    article_id    NUMBER       NOT NULL,
    reviewer_code VARCHAR2(20) NOT NULL,
    FOREIGN KEY (article_id)    REFERENCES Article(article_id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_code) REFERENCES Organizer(code)
);

-- indexes

-- most used FK, fires in 4 triggers
CREATE INDEX idx_review_article_id
    ON Review(article_id);

-- for OP2 assignments page
CREATE INDEX idx_review_reviewer_code
    ON Review(reviewer_code);

-- composite for OP4 accepted articles query
CREATE INDEX idx_article_conf_status
    ON Article(conference_acronym, status);

-- conference_acronym is 2nd col in PK so we need a separate index for BR9
CREATE INDEX idx_membership_conf
    ON Membership(conference_acronym);

-- triggers

-- max 4 reviewers per article
CREATE OR REPLACE TRIGGER trg_br1_max_reviewers
BEFORE INSERT ON Review
FOR EACH ROW
DECLARE
    v_count INT;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM Review
    WHERE article_id = :NEW.article_id;

    IF v_count >= 4 THEN
        RAISE_APPLICATION_ERROR(-20001, 'BR1: An article cannot have more than 4 reviewers.');
    END IF;
END;
/

-- reviewer must be in the conference committee
CREATE OR REPLACE TRIGGER trg_br2_reviewer_conf_match
BEFORE INSERT OR UPDATE ON Review
FOR EACH ROW
DECLARE
    v_article_conf        VARCHAR2(50);
    v_reviewer_conf_count INT;
BEGIN
    SELECT conference_acronym INTO v_article_conf
    FROM Article WHERE article_id = :NEW.article_id; -- get the conference

    SELECT COUNT(*) INTO v_reviewer_conf_count
    FROM Membership
    WHERE organizer_code     = :NEW.reviewer_code
      AND conference_acronym = v_article_conf; -- count if reviewer is member

    IF v_reviewer_conf_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'BR2: Reviewer must be in the program committee of the conference.');
    END IF;
END;
/

-- reviewer areas must overlap with article areas
CREATE OR REPLACE TRIGGER trg_br3_reviewer_area_match
BEFORE INSERT OR UPDATE ON Review
FOR EACH ROW
DECLARE
    v_overlap INT;
BEGIN
    SELECT COUNT(*) INTO v_overlap
    FROM AreaIndication ai
    JOIN ArticleAreaIndication aai ON aai.area_acronym = ai.area_acronym
    JOIN Article art ON aai.article_id = art.article_id
    WHERE ai.organizer_code     = :NEW.reviewer_code
      AND aai.article_id        = :NEW.article_id
      AND ai.conference_acronym = art.conference_acronym;

    IF v_overlap = 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'BR3: Reviewer research areas must overlap with the article areas.');
    END IF;
END;
/

-- status can change only when all reviews done (BR5) and at least 2 exist (BR6)
CREATE OR REPLACE TRIGGER trg_br5_br6_article_status
BEFORE UPDATE OF status ON Article
FOR EACH ROW
DECLARE
    v_total_reviews     INT;
    v_completed_reviews INT;
BEGIN
    IF :OLD.status = 'pending' AND :NEW.status != 'pending' THEN

        SELECT COUNT(*)
        INTO v_total_reviews
        FROM Review
        WHERE article_id = :NEW.article_id;

        SELECT COUNT(*)
        INTO v_completed_reviews
        FROM Review
        WHERE article_id = :NEW.article_id
          AND global_score IS NOT NULL;

        IF v_total_reviews < 2 THEN
            RAISE_APPLICATION_ERROR(-20006, 'BR6: Status cannot be updated without at least 2 reviews.');
        END IF;

        IF v_total_reviews != v_completed_reviews THEN
            RAISE_APPLICATION_ERROR(-20005, 'BR5: Status cannot be updated until all assigned reviews are completed.');
        END IF;
    END IF;
END;
/

-- contact author must be one of the article authors
CREATE OR REPLACE TRIGGER trg_br8_contact_is_author
AFTER INSERT OR UPDATE ON Article
FOR EACH ROW
DECLARE
    v_is_author INT;
BEGIN
    SELECT COUNT(*) INTO v_is_author
    FROM Authorship
    WHERE article_id  = :NEW.article_id
      AND author_code = :NEW.contact_author_code;

    IF v_is_author = 0 AND NOT INSERTING THEN -- skip on insert, authorship added after
        RAISE_APPLICATION_ERROR(-20008, 'BR8: Contact author must be one of the authors of the article.');
    END IF;
END;
/

-- min 2 committee members per conference (compound trigger)
CREATE OR REPLACE TRIGGER trg_br9_min_committee
FOR DELETE ON Membership
COMPOUND TRIGGER

    TYPE t_confs IS TABLE OF VARCHAR2(50) INDEX BY PLS_INTEGER;
    g_confs t_confs;
    g_idx   PLS_INTEGER := 0;

    AFTER EACH ROW IS
    BEGIN
        g_idx := g_idx + 1;
        g_confs(g_idx) := :OLD.conference_acronym;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
        v_count INT;
    BEGIN
        FOR i IN 1..g_idx LOOP
            SELECT COUNT(*) INTO v_count
            FROM Membership
            WHERE conference_acronym = g_confs(i);

            IF v_count < 2 THEN
                RAISE_APPLICATION_ERROR(-20009,
                    'BR9: A conference must have at least 2 program committee members.');
            END IF;
        END LOOP;
    END AFTER STATEMENT;

END trg_br9_min_committee;
/

-- article accepted only if avg score >= 5
CREATE OR REPLACE TRIGGER trg_br11_acceptance_threshold
BEFORE UPDATE OF status ON Article
FOR EACH ROW
BEGIN
    IF :NEW.status = 'accepted' AND :NEW.avg_global_score < 5 THEN
        RAISE_APPLICATION_ERROR(-20011, 'BR11: An article can only be accepted if avg_global_score >= 5.');
    END IF;
END;
/

-- partners only for industrial papers
CREATE OR REPLACE TRIGGER trg_br12_industrial_paper_only
BEFORE INSERT OR UPDATE ON Contribution
FOR EACH ROW
DECLARE
    v_category VARCHAR2(50);
BEGIN
    SELECT category INTO v_category
    FROM Article
    WHERE article_id = :NEW.article_id;

    IF v_category != 'Industrial Paper' THEN
        RAISE_APPLICATION_ERROR(-20012, 'BR12: Partners can only contribute to Industrial Papers.');
    END IF;
END;
/

-- keep avg_global_score in sync (compound trigger to avoid mutating table)
CREATE OR REPLACE TRIGGER trg_br13_update_avg_score
FOR INSERT OR UPDATE OF global_score OR DELETE ON Review
COMPOUND TRIGGER

    TYPE t_ids IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    g_ids t_ids;
    g_idx PLS_INTEGER := 0;

    AFTER EACH ROW IS
    BEGIN
        g_idx := g_idx + 1;
        IF DELETING THEN
            g_ids(g_idx) := :OLD.article_id;
        ELSE
            g_ids(g_idx) := :NEW.article_id;
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
        v_avg FLOAT;
    BEGIN
        FOR i IN 1..g_idx LOOP
            SELECT NVL(AVG(global_score), 0)
            INTO v_avg
            FROM Review
            WHERE article_id = g_ids(i);

            UPDATE Article
            SET avg_global_score = v_avg
            WHERE article_id = g_ids(i);
        END LOOP;
    END AFTER STATEMENT;

END trg_br13_update_avg_score;
/

-- stored procedures

-- OP1: submit a new article
CREATE OR REPLACE PROCEDURE prc_submit_article (
    p_conf_acronym IN VARCHAR2,
    p_title IN VARCHAR2,
    p_category IN VARCHAR2,
    p_contact_code IN VARCHAR2,
    p_out_article_id OUT NUMBER
)
AS
    v_seq NUMBER;
BEGIN
    SELECT NVL(MAX(seq_number), 0) + 1 INTO v_seq
    FROM Article
    WHERE conference_acronym = p_conf_acronym;

    INSERT INTO Article (
        conference_acronym, seq_number, title, category, status, contact_author_code
    ) VALUES (
        p_conf_acronym, v_seq, p_title, p_category, 'pending', p_contact_code
    ) RETURNING article_id INTO p_out_article_id;

    INSERT INTO Authorship (article_id, author_code)
    VALUES (p_out_article_id, p_contact_code); -- contact is also an author

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- assign reviewer to article (creates a stub review)
CREATE OR REPLACE PROCEDURE prc_assign_reviewer (
    p_article_id IN NUMBER,
    p_reviewer_code IN VARCHAR2
)
AS
    v_code VARCHAR2(20);
BEGIN
    v_code := 'REV-' || p_article_id || '-' || SUBSTR(p_reviewer_code, 1, 4);

    INSERT INTO Review (
        code, review_date, article_id, reviewer_code
    ) VALUES (
        v_code, SYSDATE, p_article_id, p_reviewer_code
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- OP3: fill in a review with scores
CREATE OR REPLACE PROCEDURE prc_add_review (
    p_code IN VARCHAR2,
    p_originality IN INT,
    p_significance IN INT,
    p_quality IN INT,
    p_comments IN CLOB,
    p_content IN CLOB
)
AS
    v_global_score INT;
BEGIN
    v_global_score := ROUND((p_originality + p_significance + p_quality) / 3);

    UPDATE Review
    SET review_date = SYSDATE,
        content = p_content,
        originality = p_originality,
        significance = p_significance,
        quality = p_quality,
        global_score = v_global_score,
        comments = p_comments
    WHERE code = p_code;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- OP2: get articles assigned to a reviewer
CREATE OR REPLACE PROCEDURE prc_get_reviewer_assignments (
    p_reviewer_code IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_cursor FOR
        SELECT
            art.title,
            art.category,
            (
                SELECT LISTAGG(a.name, ', ') WITHIN GROUP (ORDER BY a.name)
                FROM Authorship auth
                JOIN Author a ON auth.author_code = a.code
                WHERE auth.article_id = art.article_id
            ) AS authors_list
        FROM Review rev
        JOIN Article art ON rev.article_id = art.article_id
        WHERE rev.reviewer_code = p_reviewer_code;
END;
/

-- OP4: accepted articles for a conference
CREATE OR REPLACE PROCEDURE prc_get_accepted_articles (
    p_acronym IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_cursor FOR
        SELECT
            art.category,
            art.title,
            a.name AS contact_author_name,
            a.email AS contact_author_email,
            art.avg_global_score
        FROM Article art
        JOIN Author a ON art.contact_author_code = a.code
        WHERE art.conference_acronym = p_acronym
          AND art.status = 'accepted'
        ORDER BY art.category, art.title;
END;
/

-- utility: create conference + committee + area indications in one call
CREATE OR REPLACE PROCEDURE util_init_conference (
    p_acronym    IN VARCHAR2,
    p_name       IN VARCHAR2,
    p_location   IN VARCHAR2,
    p_url        IN VARCHAR2,
    p_org_codes  IN VARCHAR2,
    p_area_acr   IN VARCHAR2
)
AS
    v_org   VARCHAR2(20);
    v_area  VARCHAR2(20);
    v_pos   INT;
    v_str   VARCHAR2(4000);
BEGIN
    INSERT INTO Conference (acronym, name, location, homepage_url)
    VALUES (p_acronym, p_name, p_location, p_url);

    v_str := p_org_codes || ',';
    WHILE INSTR(v_str, ',') > 0 LOOP
        v_pos := INSTR(v_str, ',');
        v_org := TRIM(SUBSTR(v_str, 1, v_pos - 1));
        v_str := SUBSTR(v_str, v_pos + 1);

        INSERT INTO Membership (organizer_code, conference_acronym)
        VALUES (v_org, p_acronym);

        DECLARE
            v_astr VARCHAR2(4000) := p_area_acr || ',';
            v_apos INT;
        BEGIN
            WHILE INSTR(v_astr, ',') > 0 LOOP
                v_apos := INSTR(v_astr, ',');
                v_area := TRIM(SUBSTR(v_astr, 1, v_apos - 1));
                v_astr := SUBSTR(v_astr, v_apos + 1);
                BEGIN
                    INSERT INTO AreaIndication
                        (organizer_code, conference_acronym, area_acronym)
                    VALUES (v_org, p_acronym, v_area);
                EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
                END;
            END LOOP;
        END;
    END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- utility: register article with multiple authors and areas
CREATE OR REPLACE PROCEDURE util_register_article (
    p_conf_acronym   IN  VARCHAR2,
    p_title          IN  VARCHAR2,
    p_category       IN  VARCHAR2,
    p_contact_code   IN  VARCHAR2,
    p_author_codes   IN  VARCHAR2,
    p_area_acronyms  IN  VARCHAR2,
    p_out_article_id OUT NUMBER
)
AS
    v_seq  NUMBER;
    v_code VARCHAR2(20);
    v_area VARCHAR2(20);
    v_pos  INT;
    v_str  VARCHAR2(4000);
BEGIN
    SELECT NVL(MAX(seq_number), 0) + 1 INTO v_seq
    FROM Article WHERE conference_acronym = p_conf_acronym;

    INSERT INTO Article (
        conference_acronym, seq_number, title, category,
        status, contact_author_code
    ) VALUES (
        p_conf_acronym, v_seq, p_title, p_category,
        'pending', p_contact_code
    ) RETURNING article_id INTO p_out_article_id;

    v_str := p_author_codes || ',';
    WHILE INSTR(v_str, ',') > 0 LOOP
        v_pos := INSTR(v_str, ',');
        v_code := TRIM(SUBSTR(v_str, 1, v_pos - 1));
        v_str := SUBSTR(v_str, v_pos + 1);
        BEGIN
            INSERT INTO Authorship (article_id, author_code)
            VALUES (p_out_article_id, v_code);
        EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
        END;
    END LOOP;

    v_str := p_area_acronyms || ',';
    WHILE INSTR(v_str, ',') > 0 LOOP
        v_pos := INSTR(v_str, ',');
        v_area := TRIM(SUBSTR(v_str, 1, v_pos - 1));
        v_str := SUBSTR(v_str, v_pos + 1);
        BEGIN
            INSERT INTO ArticleAreaIndication (article_id, area_acronym)
            VALUES (p_out_article_id, v_area);
        EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
        END;
    END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- population script

DECLARE
   v_conf_acronym VARCHAR2(50);
   v_org_code     VARCHAR2(20);
   v_author_code  VARCHAR2(20);
   v_article_id   NUMBER;
   v_review_code  VARCHAR2(20);
   v_category     VARCHAR2(50);
   v_area_acronym VARCHAR2(20);
BEGIN
   -- research areas
   INSERT INTO ResearchArea (area_acronym, area_name, description)
   VALUES ('DB_SYS', 'Database Systems', 'Storage, querying, and transaction management.');
   INSERT INTO ResearchArea (area_acronym, area_name, description)
   VALUES ('SW_ENG', 'Software Engineering', 'Software processes, testing, and architecture.');
   INSERT INTO ResearchArea (area_acronym, area_name, description)
   VALUES ('AI', 'Artificial Intelligence', 'Machine learning, reasoning, and agents.');

   -- 20 sponsors
   FOR i IN 1..20 LOOP
      INSERT INTO Sponsor (name) VALUES ('Sponsor_' || i);
   END LOOP;

   -- 480 partners
   FOR i IN 1..480 LOOP
      INSERT INTO Partner (code, name, address)
      VALUES ('P_' || i, 'Partner Corp ' || i, 'City ' || i);
   END LOOP;

   -- 3600 authors
   FOR i IN 1..3600 LOOP
      INSERT INTO Author (code, name, affiliation, address, phone, email)
      VALUES ('A_' || i, 'Author ' || i, 'Uni_' || MOD(i, 50),
              'Addr ' || i, '555-' || i, 'auth' || i || '@test.com');
   END LOOP;

   -- 100 conferences with articles, reviews, etc
   FOR c IN 1..100 LOOP
      v_conf_acronym := 'CONF_' || c;

      INSERT INTO Conference (acronym, name, location, homepage_url)
      VALUES (v_conf_acronym, 'Conference ' || c,
              'City_' || c, 'http://conf' || c || '.org');

      -- 5 sponsors per conference
      FOR s IN 1..5 LOOP
         INSERT INTO Sponsorship (sponsor_name, conference_acronym, funding_date, funded_amount)
         VALUES ('Sponsor_' || (MOD((c - 1) * 5 + s - 1, 20) + 1), v_conf_acronym, SYSDATE, 10000 + s * 1000);
      END LOOP;

      -- 4 organizers per conference
      FOR o IN 1..4 LOOP
         v_org_code := 'ORG_' || c || '_' || o;

         INSERT INTO Organizer (code, name, affiliation, address, phone, email)
         VALUES (v_org_code, 'Org ' || v_org_code, 'Affil_' || MOD(o, 10),
                 'Addr_' || o, '123-' || o, 'org' || v_org_code || '@test.com');

         INSERT INTO Membership (organizer_code, conference_acronym)
         VALUES (v_org_code, v_conf_acronym);

         -- round-robin area assignment
         v_area_acronym := CASE MOD(o, 3)
             WHEN 0 THEN 'DB_SYS'
             WHEN 1 THEN 'SW_ENG'
             ELSE        'AI'
         END;

         INSERT INTO AreaIndication (organizer_code, conference_acronym, area_acronym)
         VALUES (v_org_code, v_conf_acronym, v_area_acronym);
      END LOOP;

      -- 12 articles per conference
      FOR a IN 1..12 LOOP
         IF a <= 2 THEN v_category := 'Industrial Paper';
         ELSIF a <= 4 THEN v_category := 'Tutorial';
         ELSIF a <= 5 THEN v_category := 'Short Paper';
         ELSIF a <= 6 THEN v_category := 'Poster';
         ELSE v_category := 'Research Paper'; END IF;

         v_author_code := 'A_' || ((c - 1) * 12 + a);

         v_area_acronym := CASE MOD(a, 3)
             WHEN 0 THEN 'DB_SYS'
             WHEN 1 THEN 'SW_ENG'
             ELSE        'AI'
         END;

         INSERT INTO Article (conference_acronym, seq_number, title,
                              category, status, contact_author_code)
         VALUES (v_conf_acronym, a, 'Article ' || c || '_' || a,
                 v_category, 'pending', v_author_code)
         RETURNING article_id INTO v_article_id;

         -- 3 authors per article
         INSERT INTO Authorship (article_id, author_code)
         VALUES (v_article_id, v_author_code);
         INSERT INTO Authorship (article_id, author_code)
         VALUES (v_article_id, 'A_' || (MOD((c - 1) * 12 + a, 3600) + 1));
         INSERT INTO Authorship (article_id, author_code)
         VALUES (v_article_id, 'A_' || (MOD((c - 1) * 12 + a + 1, 3600) + 1));

         -- 2 areas per article
         INSERT INTO ArticleAreaIndication (article_id, area_acronym)
         VALUES (v_article_id, v_area_acronym);
         BEGIN
             INSERT INTO ArticleAreaIndication (article_id, area_acronym)
             VALUES (v_article_id, CASE v_area_acronym
                 WHEN 'DB_SYS' THEN 'SW_ENG'
                 WHEN 'SW_ENG' THEN 'AI'
                 ELSE 'DB_SYS'
             END);
         EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
         END;

         -- industrial papers get 2 partners
         IF v_category = 'Industrial Paper' THEN
             INSERT INTO Contribution (article_id, partner_code)
             VALUES (v_article_id, 'P_' || (MOD(a, 480) + 1));
             INSERT INTO Contribution (article_id, partner_code)
             VALUES (v_article_id, 'P_' || (MOD(a + 1, 480) + 1));
         END IF;

         -- 3 reviews per article
         FOR r IN 1..3 LOOP
             v_review_code := 'REV_' || v_article_id || '_' || r;
             v_org_code := 'ORG_' || c || '_' || r;

             BEGIN
                 INSERT INTO AreaIndication (organizer_code, conference_acronym, area_acronym)
                 VALUES (v_org_code, v_conf_acronym, v_area_acronym);
             EXCEPTION
                 WHEN DUP_VAL_ON_INDEX THEN NULL;
             END;

             INSERT INTO Review (code, review_date, content, originality,
                                 significance, quality, global_score,
                                 article_id, reviewer_code)
             VALUES (v_review_code, SYSDATE, 'Review content for article ' || v_article_id,
                     5 + MOD(r, 5), 5 + MOD(r + 1, 5), 5 + MOD(r + 2, 5),
                     ROUND((5 + MOD(r, 5) + 5 + MOD(r + 1, 5) + 5 + MOD(r + 2, 5)) / 3),
                     v_article_id, v_org_code);
         END LOOP;

      END LOOP;
   END LOOP;

   -- accept articles with good scores
   UPDATE Article SET status = 'accepted' WHERE avg_global_score >= 5;
   DBMS_OUTPUT.PUT_LINE('Accepted ' || SQL%ROWCOUNT || ' articles with avg_global_score >= 5.');

   COMMIT;
   DBMS_OUTPUT.PUT_LINE('Population complete.');
END;
/
