-- tables for the ConferenceHub schema
-- independent entities first, then bridge tables

CREATE TABLE Sponsor (
    name VARCHAR2(100) PRIMARY KEY
);

CREATE TABLE Conference (
    acronym      VARCHAR2(50)  PRIMARY KEY,
    name         VARCHAR2(100) NOT NULL,
    location     VARCHAR2(100),
    homepage_url VARCHAR2(150)
);

-- organizer = program committee member
CREATE TABLE Organizer (
    code        VARCHAR2(20)  PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    affiliation VARCHAR2(100),
    address     VARCHAR2(200),
    phone       VARCHAR2(20),
    email       VARCHAR2(100)
);

CREATE TABLE ResearchArea (
    area_acronym VARCHAR2(20)  PRIMARY KEY,
    area_name    VARCHAR2(100) NOT NULL,
    description  VARCHAR2(500)
);

CREATE TABLE Author (
    code        VARCHAR2(20)  PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    affiliation VARCHAR2(100),
    address     VARCHAR2(200),
    phone       VARCHAR2(20),
    email       VARCHAR2(100)
);

-- partner = company for industrial papers
CREATE TABLE Partner (
    code    VARCHAR2(20)  PRIMARY KEY,
    name    VARCHAR2(100) NOT NULL,
    address VARCHAR2(200)
);

CREATE TABLE Article (
    article_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conference_acronym   VARCHAR2(50)  NOT NULL,
    seq_number           INT           NOT NULL,
    title                VARCHAR2(200) NOT NULL,
    category             VARCHAR2(50)  NOT NULL
        CHECK (category IN ('Industrial Paper', 'Research Paper',
                            'Tutorial', 'Poster', 'Short Paper')),
    status               VARCHAR2(20) DEFAULT 'pending'
        CHECK (status IN ('pending', 'accepted', 'rejected')),
    avg_global_score     FLOAT DEFAULT 0.0,  -- redundant, kept in sync by trigger
    contact_author_code  VARCHAR2(20) NOT NULL,
    FOREIGN KEY (conference_acronym) REFERENCES Conference(acronym),
    FOREIGN KEY (contact_author_code) REFERENCES Author(code),
    CONSTRAINT unique_conference_seq UNIQUE (conference_acronym, seq_number)
);

-- sponsor <-> conference (N:M)
CREATE TABLE Sponsorship (
    sponsor_name       VARCHAR2(100),
    conference_acronym VARCHAR2(50),
    funding_date       DATE   NOT NULL,
    funded_amount      NUMBER NOT NULL CHECK (funded_amount > 0),
    PRIMARY KEY (sponsor_name, conference_acronym),
    FOREIGN KEY (sponsor_name)       REFERENCES Sponsor(name),
    FOREIGN KEY (conference_acronym) REFERENCES Conference(acronym)
);

-- committee membership
CREATE TABLE Membership (
    organizer_code     VARCHAR2(20),
    conference_acronym VARCHAR2(50),
    PRIMARY KEY (organizer_code, conference_acronym),
    FOREIGN KEY (organizer_code)     REFERENCES Organizer(code),
    FOREIGN KEY (conference_acronym) REFERENCES Conference(acronym)
);

-- 3-way bridge: organizer declares areas for a conference
CREATE TABLE AreaIndication (
    organizer_code     VARCHAR2(20),
    conference_acronym VARCHAR2(50),
    area_acronym       VARCHAR2(20),
    PRIMARY KEY (organizer_code, conference_acronym, area_acronym),
    FOREIGN KEY (organizer_code)     REFERENCES Organizer(code),
    FOREIGN KEY (conference_acronym) REFERENCES Conference(acronym),
    FOREIGN KEY (area_acronym)       REFERENCES ResearchArea(area_acronym)
);

CREATE TABLE Authorship (
    article_id  NUMBER,
    author_code VARCHAR2(20),
    PRIMARY KEY (article_id, author_code),
    FOREIGN KEY (article_id)  REFERENCES Article(article_id) ON DELETE CASCADE,
    FOREIGN KEY (author_code) REFERENCES Author(code)
);

CREATE TABLE ArticleAreaIndication (
    article_id   NUMBER,
    area_acronym VARCHAR2(20),
    PRIMARY KEY (article_id, area_acronym),
    FOREIGN KEY (article_id)   REFERENCES Article(article_id) ON DELETE CASCADE,
    FOREIGN KEY (area_acronym) REFERENCES ResearchArea(area_acronym)
);

-- partner <-> article, only for industrial papers (BR12 checks)
CREATE TABLE Contribution (
    article_id   NUMBER,
    partner_code VARCHAR2(20),
    PRIMARY KEY (article_id, partner_code),
    FOREIGN KEY (article_id)   REFERENCES Article(article_id) ON DELETE CASCADE,
    FOREIGN KEY (partner_code) REFERENCES Partner(code)
);

CREATE TABLE Review (
    code          VARCHAR2(20) PRIMARY KEY,
    review_date   DATE         NOT NULL,
    content       CLOB,
    originality   INT  CHECK (originality  BETWEEN 0 AND 10),
    significance  INT  CHECK (significance BETWEEN 0 AND 10),
    quality       INT  CHECK (quality      BETWEEN 0 AND 10),
    global_score  INT  CHECK (global_score BETWEEN 0 AND 10),
    comments      CLOB,
    article_id    NUMBER       NOT NULL,
    reviewer_code VARCHAR2(20) NOT NULL,
    FOREIGN KEY (article_id)    REFERENCES Article(article_id) ON DELETE CASCADE,
    FOREIGN KEY (reviewer_code) REFERENCES Organizer(code)
);
